package com.beingjavaguys.model;
// Generated 2017-05-28 06:05:05 by Hibernate Tools 5.2.3.Final

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * ContactInfo generated by hbm2java
 */
@Entity
@Table(name = "ContactInfo", catalog = "sswap")
public class ContactInfo implements java.io.Serializable {

	private int idContactInfo;
	private String name;
	private String companyName;
	private String email;
	private String phone;
	private Set<User> users = new HashSet<User>(0);

	public ContactInfo() {
	}

	public ContactInfo(int idContactInfo) {
		this.idContactInfo = idContactInfo;
	}

	public ContactInfo(int idContactInfo, String name, String companyName, String email, String phone,
			Set<User> users) {
		this.idContactInfo = idContactInfo;
		this.name = name;
		this.companyName = companyName;
		this.email = email;
		this.phone = phone;
		this.users = users;
	}

	@Id

	@Column(name = "idContactInfo", unique = true, nullable = false)
	public int getIdContactInfo() {
		return this.idContactInfo;
	}

	public void setIdContactInfo(int idContactInfo) {
		this.idContactInfo = idContactInfo;
	}

	@Column(name = "name", length = 45)
	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	@Column(name = "companyName", length = 45)
	public String getCompanyName() {
		return this.companyName;
	}

	public void setCompanyName(String companyName) {
		this.companyName = companyName;
	}

	@Column(name = "email", length = 45)
	public String getEmail() {
		return this.email;
	}

	public void setEmail(String email) {
		this.email = email;
	}

	@Column(name = "phone", length = 45)
	public String getPhone() {
		return this.phone;
	}

	public void setPhone(String phone) {
		this.phone = phone;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "contactInfo")
	public Set<User> getUsers() {
		return this.users;
	}

	public void setUsers(Set<User> users) {
		this.users = users;
	}

}
