package com.beingjavaguys.model;
// Generated 2017-05-28 06:05:05 by Hibernate Tools 5.2.3.Final

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * ProjectParticipant generated by hbm2java
 */
@Entity
@Table(name = "ProjectParticipant", catalog = "sswap")
public class ProjectParticipant implements java.io.Serializable {

	private int idProjectParticipant;
	private Project project;
	private User user;

	public ProjectParticipant() {
	}

	public ProjectParticipant(int idProjectParticipant, Project project, User user) {
		this.idProjectParticipant = idProjectParticipant;
		this.project = project;
		this.user = user;
	}

	@Id

	@Column(name = "idProjectParticipant", unique = true, nullable = false)
	public int getIdProjectParticipant() {
		return this.idProjectParticipant;
	}

	public void setIdProjectParticipant(int idProjectParticipant) {
		this.idProjectParticipant = idProjectParticipant;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "Project_idProject", nullable = false)
	public Project getProject() {
		return this.project;
	}

	public void setProject(Project project) {
		this.project = project;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "User_idUser", nullable = false)
	public User getUser() {
		return this.user;
	}

	public void setUser(User user) {
		this.user = user;
	}

}
