package com.beingjavaguys.model;
// Generated 2017-05-28 06:05:05 by Hibernate Tools 5.2.3.Final

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * ProjectCompetence generated by hbm2java
 */
@Entity
@Table(name = "ProjectCompetence", catalog = "sswap")
public class ProjectCompetence implements java.io.Serializable {

	private int idProjectCompetence;
	private CompetenceType competenceType;
	private Project project;

	public ProjectCompetence() {
	}

	public ProjectCompetence(int idProjectCompetence, CompetenceType competenceType, Project project) {
		this.idProjectCompetence = idProjectCompetence;
		this.competenceType = competenceType;
		this.project = project;
	}

	@Id

	@Column(name = "idProjectCompetence", unique = true, nullable = false)
	public int getIdProjectCompetence() {
		return this.idProjectCompetence;
	}

	public void setIdProjectCompetence(int idProjectCompetence) {
		this.idProjectCompetence = idProjectCompetence;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "Competence_idCompetence", nullable = false)
	public CompetenceType getCompetenceType() {
		return this.competenceType;
	}

	public void setCompetenceType(CompetenceType competenceType) {
		this.competenceType = competenceType;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "Project_idProject", nullable = false)
	public Project getProject() {
		return this.project;
	}

	public void setProject(Project project) {
		this.project = project;
	}

}
