package com.beingjavaguys.model;
// Generated 2017-05-28 06:05:05 by Hibernate Tools 5.2.3.Final

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * UserType generated by hbm2java
 */
@Entity
@Table(name = "UserType", catalog = "sswap")
public class UserType implements java.io.Serializable {

	private int idUserType;
	private String name;
	private Set<User> users = new HashSet<User>(0);

	public UserType() {
	}

	public UserType(int idUserType) {
		this.idUserType = idUserType;
	}

	public UserType(int idUserType, String name, Set<User> users) {
		this.idUserType = idUserType;
		this.name = name;
		this.users = users;
	}

	@Id

	@Column(name = "idUserType", unique = true, nullable = false)
	public int getIdUserType() {
		return this.idUserType;
	}

	public void setIdUserType(int idUserType) {
		this.idUserType = idUserType;
	}

	@Column(name = "name", length = 45)
	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "userType")
	public Set<User> getUsers() {
		return this.users;
	}

	public void setUsers(Set<User> users) {
		this.users = users;
	}

}
