package com.beingjavaguys.model;
// Generated 2017-05-28 06:05:05 by Hibernate Tools 5.2.3.Final

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * UserCompetence generated by hbm2java
 */
@Entity
@Table(name = "UserCompetence", catalog = "sswap")
public class UserCompetence implements java.io.Serializable {

	private int idUserCompetence;
	private CompetenceType competenceType;
	private User user;

	public UserCompetence() {
	}

	public UserCompetence(int idUserCompetence, CompetenceType competenceType, User user) {
		this.idUserCompetence = idUserCompetence;
		this.competenceType = competenceType;
		this.user = user;
	}

	@Id

	@Column(name = "idUserCompetence", unique = true, nullable = false)
	public int getIdUserCompetence() {
		return this.idUserCompetence;
	}

	public void setIdUserCompetence(int idUserCompetence) {
		this.idUserCompetence = idUserCompetence;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "CompetenceType_idCompetenceType", nullable = false)
	public CompetenceType getCompetenceType() {
		return this.competenceType;
	}

	public void setCompetenceType(CompetenceType competenceType) {
		this.competenceType = competenceType;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "User_idUser", nullable = false)
	public User getUser() {
		return this.user;
	}

	public void setUser(User user) {
		this.user = user;
	}

}
