package com.beingjavaguys.model;
// Generated 2017-05-28 06:05:05 by Hibernate Tools 5.2.3.Final

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * UserStatus generated by hbm2java
 */
@Entity
@Table(name = "UserStatus", catalog = "sswap")
public class UserStatus implements java.io.Serializable {

	private int idUserStatus;
	private String name;
	private Set<User> users = new HashSet<User>(0);

	public UserStatus() {
	}

	public UserStatus(int idUserStatus) {
		this.idUserStatus = idUserStatus;
	}

	public UserStatus(int idUserStatus, String name, Set<User> users) {
		this.idUserStatus = idUserStatus;
		this.name = name;
		this.users = users;
	}

	@Id

	@Column(name = "idUserStatus", unique = true, nullable = false)
	public int getIdUserStatus() {
		return this.idUserStatus;
	}

	public void setIdUserStatus(int idUserStatus) {
		this.idUserStatus = idUserStatus;
	}

	@Column(name = "name", length = 45)
	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "userStatus")
	public Set<User> getUsers() {
		return this.users;
	}

	public void setUsers(Set<User> users) {
		this.users = users;
	}

}
