-- MySQL Script generated by MySQL Workbench
-- nie, 28 maj 2017, 11:26:55
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema sswap
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema sswap
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `sswap` DEFAULT CHARACTER SET utf8 ;
USE `sswap` ;

-- -----------------------------------------------------
-- Table `sswap`.`UserStatus`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `sswap`.`UserStatus` (
  `idUserStatus` INT NOT NULL,
  `name` VARCHAR(45) NULL,
  PRIMARY KEY (`idUserStatus`),
  UNIQUE INDEX `idUserStatus_UNIQUE` (`idUserStatus` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `sswap`.`Faculty`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `sswap`.`Faculty` (
  `idFaculty` INT NOT NULL,
  `name` VARCHAR(45) NULL,
  `location` VARCHAR(45) NULL,
  PRIMARY KEY (`idFaculty`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `sswap`.`UserType`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `sswap`.`UserType` (
  `idUserType` INT NOT NULL,
  `name` VARCHAR(45) NULL,
  PRIMARY KEY (`idUserType`),
  UNIQUE INDEX `idUserType_UNIQUE` (`idUserType` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `sswap`.`ContactInfo`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `sswap`.`ContactInfo` (
  `idContactInfo` INT NOT NULL,
  `name` VARCHAR(45) NULL,
  `companyName` VARCHAR(45) NULL,
  `email` VARCHAR(45) NULL,
  `phone` VARCHAR(45) NULL,
  PRIMARY KEY (`idContactInfo`),
  UNIQUE INDEX `idContactInfo_UNIQUE` (`idContactInfo` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `sswap`.`User`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `sswap`.`User` (
  `idUser` INT NOT NULL AUTO_INCREMENT,
  `login` VARCHAR(20) NOT NULL,
  `password` CHAR(64) NOT NULL,
  `UserStatus_idUserStatus` INT NULL,
  `Faculty_idFaculty` INT NULL,
  `UserType_idUserType` INT NULL,
  `ContactInfo_idContactInfo` INT NULL,
  PRIMARY KEY (`idUser`),
  UNIQUE INDEX `idUser_UNIQUE` (`idUser` ASC),
  UNIQUE INDEX `login_UNIQUE` (`login` ASC, `password` ASC),
  INDEX `fk_User_UserStatus_idx` (`UserStatus_idUserStatus` ASC),
  INDEX `fk_User_Faculty1_idx` (`Faculty_idFaculty` ASC),
  INDEX `fk_User_UserType1_idx` (`UserType_idUserType` ASC),
  INDEX `fk_User_ContactInfo1_idx` (`ContactInfo_idContactInfo` ASC),
  CONSTRAINT `fk_User_UserStatus`
    FOREIGN KEY (`UserStatus_idUserStatus`)
    REFERENCES `sswap`.`UserStatus` (`idUserStatus`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_User_Faculty1`
    FOREIGN KEY (`Faculty_idFaculty`)
    REFERENCES `sswap`.`Faculty` (`idFaculty`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_User_UserType1`
    FOREIGN KEY (`UserType_idUserType`)
    REFERENCES `sswap`.`UserType` (`idUserType`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_User_ContactInfo1`
    FOREIGN KEY (`ContactInfo_idContactInfo`)
    REFERENCES `sswap`.`ContactInfo` (`idContactInfo`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `sswap`.`CompetenceType`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `sswap`.`CompetenceType` (
  `idCompetenceType` INT NOT NULL,
  `name` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`idCompetenceType`),
  UNIQUE INDEX `idCompetences_UNIQUE` (`idCompetenceType` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `sswap`.`Project`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `sswap`.`Project` (
  `idProject` INT NOT NULL,
  `name` VARCHAR(45) NULL,
  `startDate` DATE NULL,
  PRIMARY KEY (`idProject`),
  UNIQUE INDEX `idProject_UNIQUE` (`idProject` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `sswap`.`ProjectCompetence`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `sswap`.`ProjectCompetence` (
  `idProjectCompetence` INT NOT NULL,
  `Project_idProject` INT NOT NULL,
  `Competence_idCompetence` INT NOT NULL,
  PRIMARY KEY (`idProjectCompetence`),
  INDEX `fk_ProjectCompetence_Project1_idx` (`Project_idProject` ASC),
  INDEX `fk_ProjectCompetence_Competence1_idx` (`Competence_idCompetence` ASC),
  CONSTRAINT `fk_ProjectCompetence_Project1`
    FOREIGN KEY (`Project_idProject`)
    REFERENCES `sswap`.`Project` (`idProject`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_ProjectCompetence_Competence1`
    FOREIGN KEY (`Competence_idCompetence`)
    REFERENCES `sswap`.`CompetenceType` (`idCompetenceType`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `sswap`.`ProjectParticipant`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `sswap`.`ProjectParticipant` (
  `idProjectParticipant` INT NOT NULL,
  `Project_idProject` INT NOT NULL,
  `User_idUser` INT NOT NULL,
  PRIMARY KEY (`idProjectParticipant`),
  INDEX `fk_ProjectParticipant_Project1_idx` (`Project_idProject` ASC),
  INDEX `fk_ProjectParticipant_User1_idx` (`User_idUser` ASC),
  CONSTRAINT `fk_ProjectParticipant_Project1`
    FOREIGN KEY (`Project_idProject`)
    REFERENCES `sswap`.`Project` (`idProject`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_ProjectParticipant_User1`
    FOREIGN KEY (`User_idUser`)
    REFERENCES `sswap`.`User` (`idUser`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `sswap`.`Message`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `sswap`.`Message` (
  `idMessage` INT NOT NULL AUTO_INCREMENT,
  `content` TEXT NULL,
  `User_idUser` INT NOT NULL,
  PRIMARY KEY (`idMessage`),
  UNIQUE INDEX `idMessage_UNIQUE` (`idMessage` ASC),
  INDEX `fk_Message_User1_idx` (`User_idUser` ASC),
  CONSTRAINT `fk_Message_User1`
    FOREIGN KEY (`User_idUser`)
    REFERENCES `sswap`.`User` (`idUser`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `sswap`.`UserCompetence`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `sswap`.`UserCompetence` (
  `idUserCompetence` INT NOT NULL,
  `User_idUser` INT NOT NULL,
  `CompetenceType_idCompetenceType` INT NOT NULL,
  PRIMARY KEY (`idUserCompetence`),
  UNIQUE INDEX `idUserCompetence_UNIQUE` (`idUserCompetence` ASC),
  INDEX `fk_UserCompetence_User1_idx` (`User_idUser` ASC),
  INDEX `fk_UserCompetence_CompetenceType1_idx` (`CompetenceType_idCompetenceType` ASC),
  CONSTRAINT `fk_UserCompetence_User1`
    FOREIGN KEY (`User_idUser`)
    REFERENCES `sswap`.`User` (`idUser`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_UserCompetence_CompetenceType1`
    FOREIGN KEY (`CompetenceType_idCompetenceType`)
    REFERENCES `sswap`.`CompetenceType` (`idCompetenceType`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
